secu_school/views/dashboard.py
from flask import Blueprint, current_app, render_template, flash, redirect, url_for, session, logging, request, send_from_directory
from ..forms import RegisterForm, LoginForm
from passlib.hash import sha256_crypt
from functools import wraps
from os.path import join
from os import remove

from werkzeug.utils import secure_filename
from ..extensions import mysql
from ..helpers import is_logged_in


dashboard = Blueprint('dashboard', __name__, template_folder='../templates/dashboard', static_folder="../static")


# Return upload folder
@dashboard.route('/uploads/<folder>/<filename>')
def uploaded_file(folder, filename):
    filename = folder + "/" + filename
    return send_from_directory("static/images/", filename)


# User Register
@dashboard.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = sha256_crypt.encrypt(str(form.password.data))

        # Create cursor
        cur = mysql.connection.cursor()

        cur.execute("INSERT INTO users(name, email, password) VALUES(%s, %s, %s)", (name, email, password))

        # Commit to DB
        mysql.connection.commit()

        # Close connection
        cur.close()

        flash('Je account is geregistreerd in de database en je kan nu inloggen.', 'success')

        return redirect(url_for('dashboard.login'))

    return render_template('register.html', form=form)

# Login
@dashboard.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password_candidate = form.password.data

        # Create cursor
        cur = mysql.connection.cursor()

        # Get User by username
        result = cur.execute("SELECT * FROM users WHERE email = %s", [email])

        if result > 0:
            session['urls'] = []
            # Get stored hash
            data = cur.fetchone()
            password = data['password']
            name = data['name']

            # Compare pw
            if sha256_crypt.verify(password_candidate, password):
                # Logged in
                session['logged_in'] = True
                session['email'] = email
                session['name'] = name

                flash('Je bent nu ingelogd.', 'success')
                return redirect(url_for('dashboard.intranet'))
            else:
                error = 'Foute login'
                return render_template('login.html', error=error)
            cur.close()
        else:
            error = 'Email niet gevonden'
            return render_template('login.html', error=error)

    return render_template('login.html', form=form)

# Logout
@dashboard.route('/logout')
@is_logged_in
def logout():
    session.clear()
    flash('You are now logged out', 'success')
    return redirect(url_for('dashboard.login'))

# Delete Row
@dashboard.route('/deleteRow/<string:table>/<string:id>/<string:name>', methods=['POST'])
@is_logged_in
def deleteRow(table, id, name):
    # Create Cursor
    cur = mysql.connection.cursor()

    if table == 'leraren':
        cur.execute("SELECT foto FROM %s WHERE id = %s"%(table, id))
        filename = cur.fetchone()
        deleteFile(table, filename['foto'])
    # Execute
    cur.execute("DELETE FROM %s WHERE id = %s"%(table, id))

    mysql.connection.commit()

    cur.close()

    flash('%s verwijderd'%(name), 'success')

    return redirect(url_for('dashboard.intranet'))

def deleteFile(folder, filename):
    filename = folder + "/" + filename
    return remove(join(current_app.config['UPLOAD_FOLDER'], filename))

# Intranet
@dashboard.route('/intranet')
@is_logged_in
def intranet():
    cur = mysql.connection.cursor()

    cur.execute('SELECT * FROM richtingen')
    richtingen = cur.fetchall()
    cur.execute('SELECT * FROM leraren')
    leraren = cur.fetchall()
    cur.execute('''SELECT klassen.id, klassen.naam, klassen.code, CONCAT(leraren.voornaam, ' ' ,leraren.naam) AS leraar, richtingen.naam AS richting FROM klassen INNER JOIN leraren ON klassen.leraar = leraren.id INNER JOIN richtingen ON klassen.richting = richtingen.id''')
    klassen = cur.fetchall()

    return render_template('intranet.html', richtingen=richtingen, leraren=leraren, klassen=klassen)
    cur.close()

@dashboard.route('/history')
@is_logged_in
def history():
    data = []
    if 'urls' in session:
        data = session['urls']
    return  render_template('history.html',data=data)

@dashboard.after_app_request
def store_visited_urls(response):
    if 'urls' in session:
        session['urls'].append(request.url)
        session.modified = True
    # if len[session['urls']] > 5:
    #     session['urls'].pop(0)
    return response

secu_school/views/klas.py
from flask import Blueprint, render_template, flash, redirect, url_for, logging, request
from ..extensions import mysql, csrf
from ..forms import KlasForm
from ..helpers import is_logged_in

klas = Blueprint('klas', __name__, template_folder='../templates/klas')

# Add Klas
@klas.route('/add_klas', methods=['GET', 'POST'])
@is_logged_in
def add_klas():

    form = KlasForm()

    cur = mysql.connection.cursor()

    cur.execute('SELECT id, naam FROM richtingen')
    richtingen = cur.fetchall()
    cur.execute('SELECT id, naam, voornaam FROM leraren')
    leraren = cur.fetchall()

    if form.validate_on_submit():
        naam = form.naam.data
        code = form.code.data
        richting = request.form['richting']
        leraar = request.form['leraar']

        # Create cursor
        cur = mysql.connection.cursor()

        cur.execute("INSERT INTO klassen(naam, code, richting, leraar) VALUES(%s, %s, %s, %s)",(naam, code, richting, leraar))

        mysql.connection.commit()

        cur.close()

        flash('Klas Aangemaakt', 'success')

        return redirect(url_for('dashboard.intranet'))
    return render_template('add_klas.html', form=form, richtingen = richtingen, leraren = leraren)
    cur.close()

# Edit Klas
@klas.route('/edit_klas/<string:id>', methods=['GET', 'POST'])
@is_logged_in
def edit_klas(id):
    # Create cursor
    cur = mysql.connection.cursor()

    # Get article by id
    cur.execute('SELECT * FROM klassen WHERE id=%s', [id])
    klas = cur.fetchone()

    cur.execute('SELECT id, naam FROM richtingen')
    richtingen = cur.fetchall()

    cur.execute('SELECT id, naam, voornaam FROM leraren')
    leraren = cur.fetchall()

    # Get form
    form = KlasForm()

    # Populate form fields
    form.naam.data = klas['naam']
    form.code.data = klas['code']


    if form.validate_on_submit():
        naam = request.form['naam']
        code = request.form['code']
        richting = request.form['richting']
        leraar = request.form['leraar']

        # Create cursor
        cur = mysql.connection.cursor()

        cur.execute("UPDATE klassen SET naam=%s, code=%s, richting=%s, leraar=%s WHERE id = %s", (naam, code, richting, leraar, id))

        mysql.connection.commit()

        cur.close()

        flash('Klas Updated', 'success')

        return redirect(url_for('dashboard.intranet'))

    return render_template('edit_klas.html', form=form, klas=klas, richtingen=richtingen, leraren=leraren)

secu_school/views/leraar.py
from flask import Blueprint, render_template, flash, redirect, url_for, logging, request, current_app
from ..forms import LeraarForm
from os.path import join
from ..extensions import mysql
from ..helpers import deleteFile, is_logged_in, allowed_file
from werkzeug.utils import secure_filename



leraar = Blueprint('leraar', __name__, template_folder='../templates/leraar')


# Add Leraren
@leraar.route('/add_leraar', methods=['GET', 'POST'])
@is_logged_in
def add_leraar():
    form = LeraarForm()
    if form.validate_on_submit():
         # check if the post request has the file part
        if 'file' not in request.files:
            flash('Geen foto gevonden.', 'danger')
            return redirect(request.url)

        file = request.files['file']
        filename = file.filename
        naam = form.naam.data
        voornaam = form.voornaam.data
        email = request.form['email']

        # if user does not select file, browser also
        # submit a empty part without filename
        if file.filename == '':
            flash('Geen foto geselecteerd')
            return redirect(request.url)

        # UPLOAD TO DB
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(join(current_app.config['UPLOAD_FOLDER'], 'leraren/' + filename))
            # Create cursor
            cur = mysql.connection.cursor()

            cur.execute("INSERT INTO leraren(foto, naam, voornaam, email) VALUES(%s, %s, %s, %s)", (filename, naam, voornaam, email))

            mysql.connection.commit()

            cur.close()

            flash('Leerkracht Toegevoegd', 'success')

            return redirect(url_for('dashboard.intranet'))

    return render_template('add_leraar.html', form=form)


# Edit Leraren
@leraar.route('/edit_leraar/<string:id>', methods=['GET', 'POST'])
@is_logged_in
def edit_leraar(id):
    # Create cursor
    cur = mysql.connection.cursor()

    # Get article by id
    result = cur.execute('SELECT * FROM leraren WHERE id=%s', [id])

    leraar = cur.fetchone()

    # Get form
    form = LeraarForm()

    # Populate leraar form fields
    form.naam.data = leraar['naam']
    form.voornaam.data = leraar['voornaam']
    form.email.data = leraar['email']


    if form.validate_on_submit():
        naam = request.form['naam']
        voornaam = request.form['voornaam']
        email = request.form['email']

         # check if the post request has the file part
        if 'file' not in request.files:
            # Update db
            cur = mysql.connection.cursor()

            cur.execute("UPDATE leraren SET naam=%s, voornaam=%s, email=%s WHERE id = %s", (naam, voornaam, email, id))

            mysql.connection.commit()

            flash('Leraar Updated', 'success')

            return redirect(url_for('dashboard.intranet'))

        file = request.files['file']
        filename = file.filename

        # if user does not select file, browser also
        # submit a empty part without filename
        if file.filename == '':
            # Update db
            cur = mysql.connection.cursor()

            cur.execute("UPDATE leraren SET naam=%s, voornaam=%s, email=%s WHERE id = %s", (naam, voornaam, email, id))

            mysql.connection.commit()

        # UPLOAD TO DB
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(join(current_app.config['UPLOAD_FOLDER'], 'leraren/' + filename))

            # Update db
            cur = mysql.connection.cursor()

            cur.execute("SELECT foto FROM leraren WHERE id = %s"%(id))
            old_filename = cur.fetchone()
            deleteFile("leraren", old_filename['foto'])

            cur.execute("UPDATE leraren SET naam=%s, voornaam=%s, foto=%s, email=%s WHERE id = %s", (naam, voornaam, filename, email, id))

            mysql.connection.commit()

        flash('Leraar Updated', 'success')

        return redirect(url_for('dashboard.intranet'))
    return render_template('edit_leraar.html', form=form, leraar=leraar)
    cur.close()

secu_school/views/richting.py
from flask import Blueprint, render_template, flash, redirect, url_for, logging, request, session
from ..forms import RichtingForm
from ..extensions import mysql
from functools import wraps

richting = Blueprint('richting', __name__, template_folder='../templates/richting')


# Check if user logged in
def is_logged_in(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else:
            flash("Unauthorized, Please login", 'danger')
            return redirect(url_for('dashboard.login'))
    return wrap

# Add Richting
@richting.route('/add_richting', methods=['GET', 'POST'])
@is_logged_in
def add_richting():

    form = RichtingForm()

    if form.validate_on_submit():
        naam = form.naam.data
        omschrijving = form.omschrijving.data

        # Create cursor
        cur = mysql.connection.cursor()

        cur.execute("INSERT INTO richtingen(naam, omschrijving) VALUES(%s, %s)",(naam, omschrijving))

        mysql.connection.commit()

        cur.close()

        flash('Richting Aangemaakt', 'success')

        return redirect(url_for('dashboard.intranet'))
    return render_template('add_richting.html', form=form)

# Edit Richting
@richting.route('/edit_richting/<string:id>', methods=['GET', 'POST'])
@is_logged_in
def edit_richting(id):
    # Create cursor
    cur = mysql.connection.cursor()

    # Get article by id
    result = cur.execute('SELECT * FROM richtingen WHERE id=%s', [id])

    richting = cur.fetchone()

    # Get form
    form = RichtingForm()

    # Populate article form fields
    form.naam.data = richting['naam']
    form.omschrijving.data = richting['omschrijving']

    if form.validate_on_submit():
        naam = request.form['naam']
        omschrijving = request.form['omschrijving']

        # Create cursor
        cur = mysql.connection.cursor()

        cur.execute("UPDATE richtingen SET naam=%s, omschrijving=%s WHERE id = %s", (naam, omschrijving, id))

        mysql.connection.commit()

        cur.close()

        flash('Richting Updated', 'success')

        return redirect(url_for('dashboard.intranet'))
    return render_template('edit_richting.html', form=form, richting=richting)

secu_school/templates/dashboard/history.html
{% extends 'layout.html' %}

{% block title %}
History
{% endblock %}

{% block body %}
<h1>History</h1>
<ul class="list-group">
  {% for item in data %}
  <li class="list-item">{{item}}</li>
  {% endfor %}
</ul>

{% endblock %}

secu_school/templates/dashboard/intranet.html
{% extends 'layout.html' %}

{% block title %}
Intranet
{% endblock %}

{% block body %}

<h1><small>Welcome {{session.name}}, to the </small>Intranet</h1>
<hr>
<a href="{{ url_for('richting.add_richting') }}" class="btn btn-outline-dark">Voeg een Richting toe</a>
<a href="{{ url_for('leraar.add_leraar') }}" class="btn btn-outline-dark">Voeg een Leraar toe</a>
<a href="{{ url_for('klas.add_klas') }}" class="btn btn-outline-dark">Voeg een Klas toe</a>
<hr>
<div id="accordion" role="tablist">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <a class="collapsed text-dark" data-toggle="collapse" href="#collapseOne" role="button" aria-expanded="false" aria-controls="collapseOne">
          Richtingen
        </a>
      </h5>
    </div>

    <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        <table class="table table-striped">
          <tr>
            <th>Naam</th>
            <th>Omschrijving</th>
            <th></th>
            <th></th>
          </tr>
          {% for richting in richtingen %}
            <tr>
              <td>{{richting.naam}}</td>
              <td>{{richting.omschrijving | safe}}</td>
              <td><a href="edit_richting/{{richting.id}}" class="btn btn-warning">Edit</a></td>
              <td>
                <form action="{{url_for('dashboard.deleteRow', table='richtingen', id=richting.id, name=richting.naam)}}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                  <input type="hidden" name="_method" value="DELETE">
                  <input type="submit" value="Delete" class="btn btn-danger">
                </form>
              </td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" role="tab" id="headingTwo">
      <h5 class="mb-0">
        <a class="collapsed text-dark" data-toggle="collapse" href="#collapseTwo" role="button" aria-expanded="false" aria-controls="collapseTwo">
          Leraren
        </a>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        <table class="table table-striped">
          <tr>
            <th>Foto</th>
            <th>Naam</th>
            <th>Email</th>
            <th></th>
            <th></th>
          </tr>
          {% for leraar in leraren %}
            <tr>
              <td><img class="mw-150px" src="{{ url_for('dashboard.uploaded_file', folder='leraren', filename=leraar.foto) }}" alt="Foto {{leraar.naam}} {{leraar.voornaam}}"></td>
              <td>{{leraar.voornaam}} {{leraar.naam}}</td>
              <td>{{leraar.email}}</td>
              <td><a href="edit_leraar/{{leraar.id}}" class="btn btn-warning">Edit</a></td>
              <td>
                <form action="{{url_for('dashboard.deleteRow', table='leraren', id=leraar.id, name=leraar.naam+" "+leraar.voornaam)}}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                  <input type="hidden" name="_method" value="DELETE">
                  <input type="submit" value="Delete" class="btn btn-danger">
                </form>
              </td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" role="tab" id="headingThree">
      <h5 class="mb-0">
        <a class="collapsed text-dark" data-toggle="collapse" href="#collapseThree" role="button" aria-expanded="false" aria-controls="collapseThree">
          Klassen
        </a>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
        <table class="table table-striped">
          <tr>
            <th>Naam</th>
            <th>Code</th>
            <th>Richting</th>
            <th>Leraar</th>
            <th></th>
            <th></th>
          </tr>
          {% for klas in klassen %}
            <tr>
              <td>{{klas.naam}}</td>
              <td>{{klas.code}}</td>
              <td>{{klas.richting}}</td>
              <td>{{klas.leraar}}</td>
              <td><a href="edit_klas/{{klas.id}}" class="btn btn-warning">Edit</a></td>
              <td>
                <form action="{{url_for('dashboard.deleteRow', table='klassen', id=klas.id, name=klas.naam)}}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                  <input type="hidden" name="_method" value="DELETE">
                  <input type="submit" value="Delete" class="btn btn-danger">
                </form>
              </td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

secu_school/templates/dashboard/login.html
{% extends 'layout.html' %}
{% from "includes/_formhelpers.html" import render_field %}

{% block title %}
Login
{% endblock %}

{% block body %}

<h1>Login</h1>
<form action="" method="post">
  <div class="form-group">
      {{render_field(form.email, class_="form-control")}}
    <p class="text-muted">admin@secundaireschool.be</p>
  </div>
  <div class="form-group">
    {{render_field(form.password, class_="form-control")}}
    <p class="text-muted">123456</p>
  </div>
  {{ form.csrf_token }}
  <p><input type="submit" class="btn btn-primary" value="Submit"></p>
</form>

{% endblock %}

secu_school/templates/dashboard/register.html
{% extends 'layout.html' %}
{% from "includes/_formhelpers.html" import render_field %}

{% block title %}
Register
{% endblock %}

{% block body %}

<h1>Register</h1>
<form action="" method="post">
  <div class="form-group">
    {{render_field(form.name, class_="form-control")}}
  </div>
  <div class="form-group">
    {{render_field(form.email, class_="form-control")}}
  </div>
  <div class="form-group">
    {{render_field(form.password, class_="form-control")}}
  </div>
  <div class="form-group">
    {{render_field(form.confirm, class_="form-control")}}
  </div>
  {{ form.csrf_token }}
  <p><input type="submit" class="btn btn-primary" value="Submit"></p>
</form>

{% endblock %}